apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: orderflow-agent:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: LOKI_URL
              value: "http://loki.monitoring.svc.cluster.local:3100"
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: GROQ_API_KEY
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: SLACK_WEBHOOK_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
